/**
 * Generated by tsnapi — public API snapshot of `verkit`
 */
// #region Interfaces
export interface CoerceOptions extends VersionOptions {
  includePrerelease?: boolean;
  rtl?: boolean;
}
export interface IncrementOptions extends VersionOptions {
  identifier?: string;
  identifierBase?: 0 | 1 | false;
}
export interface RangeOptions extends VersionOptions {
  includePrerelease?: boolean;
}
export interface SemVer {
  major: number;
  minor: number;
  patch: number;
  prerelease?: PrereleaseIdentifier[] | undefined;
  build?: string[] | undefined;
}
export interface SemVerComparator {
  operator: "" | "<" | "<=" | ">" | ">=";
  options: RangeOptions;
  value: string;
  version: SemVer | null;
}
export interface SemVerRange {
  normalized: string;
  options: RangeOptions;
  raw: string;
  sets: SemVerComparator[][];
}
export interface VersionOptions {
  loose?: boolean;
}
// #endregion

// #region Types
export type Comparison = -1 | 0 | 1;
export type ComparisonOperator = "" | "!=" | "!==" | "<" | "<=" | "=" | "==" | "===" | ">" | ">=";
export type IncrementType = "major" | "minor" | "patch" | "premajor" | "preminor" | "prepatch" | "prerelease" | "release";
export type PrereleaseIdentifier = number | string;
export type RangeDirection = "<" | ">";
export type RangeInput = SemVerRange | string;
export type TruncationType = Exclude<IncrementType, "release">;
export type VersionDifference = "major" | "minor" | "patch" | "premajor" | "preminor" | "prepatch" | "prerelease";
export type VersionInput = SemVer | string;
// #endregion

// #region Functions
export declare function clean(_: VersionInput, _?: VersionOptions): string | null;
export declare function coerce(_: number | VersionInput, _?: CoerceOptions): string | null;
export declare function comparatorsIntersect(_: string, _: string, _?: RangeOptions): boolean;
export declare function compare(_: VersionInput, _: VersionInput, _?: VersionOptions): Comparison;
export declare function compareBuild(_: VersionInput, _: VersionInput, _?: VersionOptions): Comparison;
export declare function compareIdentifiers(_: PrereleaseIdentifier, _: PrereleaseIdentifier): Comparison;
export declare function compareIdentifiersReversed(_: PrereleaseIdentifier, _: PrereleaseIdentifier): Comparison;
export declare function compareMain(_: VersionInput, _: VersionInput, _?: VersionOptions): Comparison;
export declare function comparePrerelease(_: VersionInput, _: VersionInput, _?: VersionOptions): Comparison;
export declare function compareReversed(_: VersionInput, _: VersionInput, _?: VersionOptions): Comparison;
export declare function compareWithOperator(_: VersionInput, _: ComparisonOperator, _: VersionInput, _?: VersionOptions): boolean;
export declare function difference(_: VersionInput, _: VersionInput): VersionDifference | null;
export declare function findMaxSatisfying<T extends VersionInput>(_: readonly T[], _: string, _?: RangeOptions): T | null;
export declare function findMaxSatisfying<T extends VersionInput>(_: readonly T[], _: RangeInput): T | null;
export declare function findMinimumForRange(_: string, _?: RangeOptions): string | null;
export declare function findMinimumForRange(_: RangeInput): string | null;
export declare function findMinSatisfying<T extends VersionInput>(_: readonly T[], _: string, _?: RangeOptions): T | null;
export declare function findMinSatisfying<T extends VersionInput>(_: readonly T[], _: RangeInput): T | null;
export declare function getBuild(_: VersionInput, _?: VersionOptions): string[] | null;
export declare function getMajor(_: VersionInput, _?: VersionOptions): number;
export declare function getMinor(_: VersionInput, _?: VersionOptions): number;
export declare function getPatch(_: VersionInput, _?: VersionOptions): number;
export declare function getPrerelease(_: VersionInput, _?: VersionOptions): PrereleaseIdentifier[] | null;
export declare function increment(_: VersionInput, _: IncrementType, _?: IncrementOptions): string | null;
export declare function isEqual(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isGreater(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isGreaterOrEqual(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isGreaterThanRange(_: VersionInput, _: string, _?: RangeOptions): boolean;
export declare function isGreaterThanRange(_: VersionInput, _: RangeInput): boolean;
export declare function isLess(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isLessOrEqual(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isLessThanRange(_: VersionInput, _: string, _?: RangeOptions): boolean;
export declare function isLessThanRange(_: VersionInput, _: RangeInput): boolean;
export declare function isNotEqual(_: VersionInput, _: VersionInput, _?: VersionOptions): boolean;
export declare function isOutsideRange(_: VersionInput, _: string, _: RangeDirection, _?: RangeOptions): boolean;
export declare function isOutsideRange(_: VersionInput, _: RangeInput, _: RangeDirection): boolean;
export declare function isPrerelease(_: VersionInput, _?: VersionOptions): boolean | null;
export declare function isRangeSubset(_: string, _: string, _?: RangeOptions): boolean;
export declare function isRangeSubset(_: RangeInput, _: RangeInput): boolean;
export declare function isStable(_: VersionInput, _?: VersionOptions): boolean | null;
export declare function isValid(_: VersionInput, _?: VersionOptions): boolean;
export declare function isValidRange(_: string, _?: RangeOptions): boolean;
export declare function isValidRange(_: RangeInput): boolean;
export declare function normalize(_: VersionInput, _?: VersionOptions): string | null;
export declare function normalizeComparator(_: string, _?: RangeOptions): string;
export declare function normalizeFull(_: VersionInput, _?: VersionOptions): string | null;
export declare function normalizeRange(_: string, _?: RangeOptions): string | null;
export declare function normalizeRange(_: RangeInput): string | null;
export declare function parse(_: VersionInput, _?: VersionOptions): SemVer;
export declare function parseRange(_: string, _?: RangeOptions): SemVerRange;
export declare function parseRange(_: RangeInput): SemVerRange;
export declare function rangesIntersect(_: string, _: string, _?: RangeOptions): boolean;
export declare function rangesIntersect(_: RangeInput, _: RangeInput): boolean;
export declare function rangeToComparators(_: string, _?: RangeOptions): string[][];
export declare function rangeToComparators(_: RangeInput): string[][];
export declare function satisfies(_: VersionInput, _: string, _?: RangeOptions): boolean;
export declare function satisfies(_: VersionInput, _: RangeInput): boolean;
export declare function satisfiesComparator(_: VersionInput, _: string, _?: RangeOptions): boolean;
export declare function simplifyRange<T extends VersionInput>(_: readonly T[], _: string, _?: RangeOptions): string;
export declare function simplifyRange<T extends VersionInput>(_: readonly T[], _: RangeInput): string;
export declare function sort<T extends VersionInput>(_: readonly T[], _?: VersionOptions): T[];
export declare function sortReversed<T extends VersionInput>(_: readonly T[], _?: VersionOptions): T[];
export declare function truncate(_: VersionInput, _: TruncationType, _?: VersionOptions): string | null;
export declare function tryParse(_: VersionInput, _?: VersionOptions): SemVer | null;
export declare function tryParseRange(_: string, _?: RangeOptions): SemVerRange | null;
export declare function tryParseRange(_: RangeInput): SemVerRange | null;
// #endregion

// #region Variables
export declare const INCREMENT_TYPES: readonly IncrementType[];
export declare const SEMVER_SPEC_VERSION: string;
export declare const TRUNCATION_TYPES: readonly TruncationType[];
// #endregion